game: sliding_puzzle
margin_k: 2
max_steps: 200
max_agents_per_step: 3
output_dir: output
temperature: 0.1
temp_escalation: false

# Game-specific
#initial_state: [15,14,13,12,11,10, 9, 8, 7, 6, 5, 4, 3, 1, 2, 0]
# initial_state: [0, 1, 2, 3,6,7,8,4,5,14,10,12,9,13,11,15]
initial_state: [0, 1, 2, 5, 6, 3, 4, 7, 8]
# Fallback config
max_fallback_retries: 3
fallback_api: gemini # "gemini" | "local" | "both"
fallback_local_model: deepseek-ai/DeepSeek-R1-Distill-Qwen-32B
gemini_model: gemini-2.5-flash

llm_backend: huggingface          # "huggingface" | "ollama"
ollama_model: qwen3:8b
