name: Download Model to Cluster

on:
  push:
    branches: [dev/download]

env:
  REPO_PATH: /pfs/data6/home/ul/ul_student/ul_hfj15/Lecuture-AGI-Project

jobs:
  download-model:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: dev/download

      - name: Download model
        run: uv run LLM/download.py

      - name: Copy model to LLM/static on cluster
        run: |
          mkdir -p ${{ env.REPO_PATH }}/LLM/static
          cp -rv LLM/model/* ${{ env.REPO_PATH }}/LLM/static/
